name: CI
on:
  push:
    branches:
      - "main"
      - "dev"
  pull_request:
    branches:
      - "main"
env:
  GO_VERSION: 1.17

jobs:
  test-ci-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}